hospital:
  name: Medcurial Inc.
  address: Ortigas Center, Pasig City, Philippines
  hotline: 1234567
  er-hotline: 7654321
  website: exist.com.ph
  logo: https://github.com/erx-medcurial/config-server/blob/master/logo.png?raw=true
  
billing:
  senior-discount-rate: 20%
  pwd-discount-rate: 20%
  room:
    charge:
      cutoff: 0 15 12,23 * * ?
  quantity:
    multiplier:
      deposit: 2

clinical:
  document-locking:
    discharge-summary: 5

